spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jalmenarez/spring-cloud-microservices
          searchPaths: config-repo

server.port: 8000

endpoints:
  restart:
    enabled: true