---
spring:
  profiles:
    active: local
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jalmenarez/spring-cloud-microservices
          searchPaths: config-repo

server.port: 8000

endpoints:
  restart:
    enabled: true
---
spring:
  profiles: local
  
info:
  datacenter: local
  app:
    name: "@project.name@"
    description: "@project.description@"
  build:
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"

logging:
  level: 
    root: INFO
  path: /
---
spring:
  profiles: cloud

info:
  datacenter: Amazon
  app:
    name: "@project.name@"
    description: "@project.description@"
  build:
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"

logging:
  level: 
    root: WARN
    org.springframework.web: DEBUG
  path: /var/log/microservices